services:
    phpbbstudio.tlink.listener:
        class: phpbbstudio\tlink\event\main
        arguments:
            - '@auth'
            - '@language'
            - '@request'
        tags:
            - { name: event.listener }
